-- =============================================================================
-- FOMENTO-ONASP — Schema PostgreSQL preliminar
-- Fonte: backend/db/init-db.js (SQLite)
-- Gerado em: 2026-05-27
-- Status: PRELIMINAR — não executar contra banco sem revisão humana
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. parametros_minimos
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parametros_minimos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uf text NOT NULL,
  parametro text NOT NULL,
  status text NOT NULL,
  atualizado_em timestamptz,
  -- Colunas adicionadas via ALTER no init-db.js
  quantidade_atual numeric,
  quantidade_ideal numeric,
  resposta_original text,
  UNIQUE (uf, parametro)
);

-- ---------------------------------------------------------------------------
-- 2. formalizacao_profor
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS formalizacao_profor (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uf text NOT NULL,
  etapa text NOT NULL,
  status text NOT NULL,
  observacao text,
  atualizado_em timestamptz,
  UNIQUE (uf, etapa)
);

-- ---------------------------------------------------------------------------
-- 3. orcamento_2026
-- NOTA: PK é text (não autoincrement) — preservado como no SQLite.
-- Esta tabela possui ~60 colunas adicionadas via garantirColuna + garantirColunasOrcamentoRastreio.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orcamento_2026 (
  id text PRIMARY KEY,
  categoria text,
  descricao text,
  acao_orcamentaria text,
  plano_orcamentario text,
  natureza text,
  valor_previsto numeric(15,2) DEFAULT 0,
  valor_disponibilizado numeric(15,2) DEFAULT 0,
  valor_empenhado numeric(15,2) DEFAULT 0,
  valor_executado numeric(15,2) DEFAULT 0,
  status text,
  setor_atual text,
  responsavel_atual text,
  data_entrada_setor date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.
  pendencia_atual text,
  observacao text,
  classificacao_gerencial text DEFAULT 'NAO_APARELHAMENTO',
  atualizado_em timestamptz,

  -- Colunas adicionadas via garantirColuna (linhas 60-75 do init-db.js)
  processo_pai_id text,
  tipo_processo text DEFAULT 'PRINCIPAL',
  origem_recurso_id text,
  ordem_exibicao integer,
  valor_alocado_origem numeric(15,2) DEFAULT 0,
  valor_estimado_pesquisa_preco numeric(15,2) DEFAULT 0,
  -- NOTA: valor_empenhado já declarado na definição original do CREATE TABLE (linha 33).
  -- A chamada garantirColuna na linha 66 é redundante (idempotente no SQLite).
  -- Não duplicamos aqui.
  processo_autuado boolean DEFAULT false, -- SQLite: INTEGER DEFAULT 0
  pena_justa boolean DEFAULT false,       -- SQLite: INTEGER DEFAULT 0
  processo_sei text,
  -- NOTA: setor_atual, responsavel_atual, data_entrada_setor, pendencia_atual
  -- já declarados acima. As chamadas garantirColuna (linhas 69-72) são redundantes.
  compoe_orcamento boolean DEFAULT true, -- SQLite: INTEGER DEFAULT 1
  ativo boolean DEFAULT true,             -- SQLite: INTEGER DEFAULT 1
  -- NOTA: classificacao_gerencial já declarado acima. Linha 75 é redundante.

  -- Colunas de rastreio (garantirColunasOrcamentoRastreio, linhas 88-150)
  tipo_rastreio text,
  abrangencia text,
  quantidade text, -- INCERTEZA: "quantidade" como TEXT no SQLite — pode ser texto descritivo, preservado como text
  unidade text,
  valor_unitario numeric(15,2) DEFAULT 0,

  -- Etapa: Processo SEI
  link_processo_sei text,
  data_processo_sei date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Demanda formalizada
  demanda_formalizada text,
  link_demanda_formalizada text,
  data_demanda_formalizada date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Estudo técnico
  estudo_tecnico text,
  link_estudo_tecnico text,
  data_estudo_tecnico date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Termo de referência
  termo_referencia text,
  link_termo_referencia text,
  data_termo_referencia date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Pesquisa de preços
  pesquisa_precos text,
  link_pesquisa_precos text,
  data_pesquisa_precos date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Autorização da autoridade
  autorizacao_autoridade text,
  link_autorizacao_autoridade text,
  data_autorizacao_autoridade date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Parecer jurídico
  parecer_juridico text,
  link_parecer_juridico text,
  data_parecer_juridico date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Empenho
  empenho text,
  link_empenho text,
  data_empenho date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Contrato
  contrato text,
  link_contrato text,
  data_contratacao date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Ordem de serviço
  ordem_servico text,
  link_ordem_servico text,
  data_ordem_servico date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Entrega
  data_entrega date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa: Ordem bancária
  ordem_bancaria text,
  link_ordem_bancaria text,
  data_ordem_bancaria date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa PROFOR: Autuação
  profor_autuacao text,
  link_profor_autuacao text,
  data_profor_autuacao date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa PROFOR: Parecer técnico
  profor_parecer_tecnico text,
  link_profor_parecer_tecnico text,
  data_profor_parecer_tecnico date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa PROFOR: Minuta do edital
  profor_minuta_edital text,
  link_profor_minuta_edital text,
  data_profor_minuta_edital date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa PROFOR: DDO/CGOF
  profor_ddo_cgof text,
  link_profor_ddo_cgof text,
  data_profor_ddo_cgof date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa PROFOR: Abertura do programa
  profor_abertura_programa text,
  link_profor_abertura_programa text,
  data_profor_abertura_programa date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa PROFOR: Parecer CONJUR
  profor_parecer_conjur text,
  link_profor_parecer_conjur text,
  data_profor_parecer_conjur date, -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.

  -- Etapa PROFOR: Publicação GABSEC
  profor_publicacao_gabsec text,
  link_profor_publicacao_gabsec text,
  data_profor_publicacao_gabsec date -- Datas de origem em DD/MM/YYYY no SQLite; converter para YYYY-MM-DD no script de importação.
);

-- ---------------------------------------------------------------------------
-- 4. historico_alteracoes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS historico_alteracoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pagina text NOT NULL,
  registro text NOT NULL,
  campo text NOT NULL,
  valor_anterior text,
  valor_novo text,
  alterado_em timestamptz NOT NULL
);

-- ---------------------------------------------------------------------------
-- 5. orcamento_2026_movimentacoes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orcamento_2026_movimentacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo text NOT NULL,
  origem_id text,
  destino_id text,
  valor numeric(15,2) NOT NULL DEFAULT 0,
  justificativa text,
  criado_em timestamptz NOT NULL,
  criado_por text,
  ativo boolean DEFAULT true -- SQLite: INTEGER DEFAULT 1
);

-- ---------------------------------------------------------------------------
-- 6. profor_convenios_monitorados
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_convenios_monitorados (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_convenio text NOT NULL,
  ano text,
  uf text,
  instrumento text DEFAULT 'Convênio',
  programa_origem text DEFAULT 'PROFOR 2022',
  ativo boolean DEFAULT true, -- SQLite: INTEGER DEFAULT 1
  id_convenio_transferegov text,
  observacao text,
  criado_em timestamptz,
  atualizado_em timestamptz,
  UNIQUE (numero_convenio, ano)
);

-- ---------------------------------------------------------------------------
-- 7. profor_detru_cache
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_detru_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_convenio text NOT NULL,
  ano text,
  payload_json jsonb NOT NULL, -- SQLite: TEXT NOT NULL
  fonte text DEFAULT 'DETRU/siconv_convenio.csv.zip',
  arquivo_origem text,
  arquivo_hash text,
  consultado_em timestamptz NOT NULL,
  atualizado_em timestamptz NOT NULL,
  UNIQUE (numero_convenio, ano)
);

-- ---------------------------------------------------------------------------
-- 8. profor_detru_atualizacoes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_detru_atualizacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iniciado_em timestamptz NOT NULL,
  concluido_em timestamptz,
  sucesso boolean DEFAULT false, -- SQLite: INTEGER DEFAULT 0
  caminho_arquivo text,
  arquivo_hash text,
  total_carteira_ativa integer DEFAULT 0,
  total_linhas_detru_lidas integer DEFAULT 0,
  total_encontrados integer DEFAULT 0,
  total_nao_encontrados integer DEFAULT 0,
  erro text,
  resumo_json jsonb -- SQLite: TEXT
);

-- ---------------------------------------------------------------------------
-- 9. profor_transferegov_rendimentos_cache
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_transferegov_rendimentos_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_convenio text NOT NULL,
  ano text,
  saldo_rendimentos_atual numeric(15,2),
  valor_original text, -- INCERTEZA: nome sugere monetário mas tipo original é TEXT (pode ser string formatada)
  subtitulo text,
  aviso text,
  convenio_texto text,
  url_final text,
  consultado_em timestamptz NOT NULL,
  atualizado_em timestamptz NOT NULL,
  sucesso boolean DEFAULT true, -- SQLite: INTEGER DEFAULT 1
  erro text,
  payload_json jsonb, -- SQLite: TEXT
  UNIQUE (numero_convenio, ano)
);

-- ---------------------------------------------------------------------------
-- 10. profor_transferegov_rendimentos_consultas
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_transferegov_rendimentos_consultas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iniciado_em timestamptz NOT NULL,
  concluido_em timestamptz,
  sucesso boolean DEFAULT false, -- SQLite: INTEGER DEFAULT 0
  total_carteira_ativa integer DEFAULT 0,
  total_consultados integer DEFAULT 0,
  total_sucesso integer DEFAULT 0,
  total_falha integer DEFAULT 0,
  erro text,
  resumo_json jsonb -- SQLite: TEXT
);

-- ---------------------------------------------------------------------------
-- 11. logs_operacionais
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS logs_operacionais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modulo text NOT NULL,
  tipo_evento text NOT NULL,
  status text NOT NULL,
  iniciado_em timestamptz,
  concluido_em timestamptz,
  duracao_ms integer,
  resumo text,
  payload_json jsonb, -- SQLite: TEXT
  criado_em timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_logs_operacionais_criado_em ON logs_operacionais(criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_logs_operacionais_tipo_evento ON logs_operacionais(tipo_evento);
CREATE INDEX IF NOT EXISTS idx_logs_operacionais_status ON logs_operacionais(status);

-- ---------------------------------------------------------------------------
-- 12. profor_2022_rateio_import_lotes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_2022_rateio_import_lotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  arquivo_origem text NOT NULL,
  arquivo_json_dry_run text NOT NULL,
  hash_arquivo_json text,
  status text NOT NULL,
  total_itens integer NOT NULL DEFAULT 0,
  total_rateios integer NOT NULL DEFAULT 0,
  total_alertas integer NOT NULL DEFAULT 0,
  total_alertas_impeditivos integer NOT NULL DEFAULT 0,
  observacao text,
  rollback_em timestamptz,
  rollback_motivo text,
  criado_em timestamptz NOT NULL
);

-- ---------------------------------------------------------------------------
-- 13. profor_2022_itens_conhecidos
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_2022_itens_conhecidos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave_item text NOT NULL,
  numero_convenio text NOT NULL,
  descricao_normalizada text NOT NULL,
  descricao_original_referencia text,
  uf text,
  ano text,
  naturezas_encontradas_json jsonb NOT NULL DEFAULT '[]'::jsonb, -- SQLite: TEXT NOT NULL DEFAULT '[]'
  unidades_encontradas_json jsonb NOT NULL DEFAULT '[]'::jsonb,  -- SQLite: TEXT NOT NULL DEFAULT '[]'
  valor_unitario_referencia numeric(15,2) NOT NULL DEFAULT 0,
  origem text NOT NULL DEFAULT 'planilha-antiga',
  possui_pendencia_impeditiva integer NOT NULL DEFAULT 0, -- INCERTEZA: nome não está na lista de booleanos; mantido como integer
  apto_para_importacao_futura integer NOT NULL DEFAULT 1, -- INCERTEZA: idem; semanticamente booleano mas não listado
  status_item text NOT NULL DEFAULT 'ATIVO',
  ultima_ocorrencia_em timestamptz,
  ultima_ausencia_em timestamptz,
  validacao_exclusao text,
  item_substituido_id bigint,
  motivo_substituicao text,
  observacao_substituicao text,
  validado_por text,
  validado_em timestamptz,
  ativo boolean NOT NULL DEFAULT true, -- SQLite: INTEGER NOT NULL DEFAULT 1
  lote_importacao_id bigint,
  criado_em timestamptz NOT NULL,
  atualizado_em timestamptz NOT NULL,
  UNIQUE (chave_item),
  FOREIGN KEY (item_substituido_id) REFERENCES profor_2022_itens_conhecidos(id),
  FOREIGN KEY (lote_importacao_id) REFERENCES profor_2022_rateio_import_lotes(id)
);

-- ---------------------------------------------------------------------------
-- 14. profor_2022_item_rateios
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_2022_item_rateios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_conhecido_id bigint NOT NULL,
  chave_item text NOT NULL,
  area text NOT NULL,
  natureza text NOT NULL,
  quantidade_referencia numeric NOT NULL DEFAULT 0,
  valor_previsto_referencia numeric(15,2) NOT NULL DEFAULT 0,
  valor_executado_referencia numeric(15,2) NOT NULL DEFAULT 0,
  percentual_quantidade numeric NOT NULL DEFAULT 0,
  percentual_valor numeric NOT NULL DEFAULT 0,
  ativo boolean NOT NULL DEFAULT true, -- SQLite: INTEGER NOT NULL DEFAULT 1
  lote_importacao_id bigint,
  criado_em timestamptz NOT NULL,
  atualizado_em timestamptz NOT NULL,
  UNIQUE (item_conhecido_id, area, natureza, lote_importacao_id),
  FOREIGN KEY (item_conhecido_id) REFERENCES profor_2022_itens_conhecidos(id),
  FOREIGN KEY (lote_importacao_id) REFERENCES profor_2022_rateio_import_lotes(id)
);

-- ---------------------------------------------------------------------------
-- 15. profor_2022_rateio_import_alertas
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_2022_rateio_import_alertas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lote_importacao_id bigint NOT NULL,
  chave_item text,
  tipo text NOT NULL,
  nivel text NOT NULL,
  numero_convenio text,
  uf text,
  ano text,
  descricao text,
  detalhe text,
  origem_arquivo text,
  origem_aba text,
  origem_linha integer,
  criado_em timestamptz NOT NULL,
  FOREIGN KEY (lote_importacao_id) REFERENCES profor_2022_rateio_import_lotes(id)
);

-- ---------------------------------------------------------------------------
-- 16. profor_2022_revisao_lotes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_2022_revisao_lotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  origem text NOT NULL,
  arquivo_origem text,
  hash_origem text,
  status text NOT NULL DEFAULT 'ABERTO',
  total_divergencias integer NOT NULL DEFAULT 0,
  total_pendentes integer NOT NULL DEFAULT 0,
  total_impeditivas integer NOT NULL DEFAULT 0,
  criado_em timestamptz NOT NULL,
  atualizado_em timestamptz NOT NULL
);

-- ---------------------------------------------------------------------------
-- 17. profor_2022_revisao_divergencias
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_2022_revisao_divergencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lote_revisao_id bigint NOT NULL,
  chave_divergencia text NOT NULL,
  numero_convenio text,
  uf text,
  chave_item text,
  tipo_alerta text NOT NULL,
  nivel text NOT NULL,
  status text NOT NULL DEFAULT 'PENDENTE',
  campo_afetado text,
  valor_anterior text,
  valor_novo text,
  fonte_anterior text,
  fonte_nova text,
  diferenca text,
  motivo_provavel text,
  acao_sugerida text,
  impacto_reconstrucao text,
  bloqueia_publicacao boolean NOT NULL DEFAULT false, -- SQLite: INTEGER NOT NULL DEFAULT 0
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,     -- SQLite: TEXT NOT NULL DEFAULT '{}'
  criado_em timestamptz NOT NULL,
  atualizado_em timestamptz NOT NULL,
  UNIQUE (chave_divergencia),
  FOREIGN KEY (lote_revisao_id) REFERENCES profor_2022_revisao_lotes(id)
);

-- ---------------------------------------------------------------------------
-- 18. profor_2022_revisao_decisoes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_2022_revisao_decisoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  divergencia_id bigint NOT NULL,
  decisao text NOT NULL,
  valor_aplicado text,
  justificativa text,
  usuario text,
  decidido_em timestamptz NOT NULL,
  lote_saneamento_id bigint, -- INCERTEZA: não há FK declarada no SQLite; pode apontar para uma tabela futura
  payload_decisao_json jsonb NOT NULL DEFAULT '{}'::jsonb, -- SQLite: TEXT NOT NULL DEFAULT '{}'
  criado_em timestamptz NOT NULL,
  FOREIGN KEY (divergencia_id) REFERENCES profor_2022_revisao_divergencias(id)
);

-- ---------------------------------------------------------------------------
-- 19. profor_2022_revisao_logs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profor_2022_revisao_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidade_tipo text NOT NULL,
  entidade_id bigint, -- INCERTEZA: referencia polimórfica sem FK; mantido como bigint para consistência com PKs
  evento text NOT NULL,
  estado_anterior_json jsonb, -- SQLite: TEXT
  estado_novo_json jsonb,     -- SQLite: TEXT
  usuario text,
  detalhe text,
  criado_em timestamptz NOT NULL
);

-- ===========================================================================
-- ÍNDICES
-- ===========================================================================

-- Índices de profor_2022_itens_conhecidos
CREATE INDEX IF NOT EXISTS idx_itens_numero_convenio
  ON profor_2022_itens_conhecidos(numero_convenio);
CREATE INDEX IF NOT EXISTS idx_itens_numero_descricao
  ON profor_2022_itens_conhecidos(numero_convenio, descricao_normalizada);
CREATE INDEX IF NOT EXISTS idx_itens_apto
  ON profor_2022_itens_conhecidos(apto_para_importacao_futura);
CREATE INDEX IF NOT EXISTS idx_itens_status_item
  ON profor_2022_itens_conhecidos(status_item);

-- Índices de profor_2022_item_rateios
CREATE INDEX IF NOT EXISTS idx_rateios_item
  ON profor_2022_item_rateios(item_conhecido_id);
CREATE INDEX IF NOT EXISTS idx_rateios_chave_item
  ON profor_2022_item_rateios(chave_item);

-- Partial unique index: apenas rateios ativos
-- Postgres suporta WHERE em UNIQUE INDEX nativamente.
-- NOTA: ativo foi convertido para boolean; a condição muda de "ativo = 1" para "ativo = true".
CREATE UNIQUE INDEX IF NOT EXISTS idx_rateio_ativo_unico
  ON profor_2022_item_rateios(item_conhecido_id, area, natureza)
  WHERE ativo = true;

-- Índices de profor_2022_rateio_import_alertas
CREATE INDEX IF NOT EXISTS idx_alertas_lote
  ON profor_2022_rateio_import_alertas(lote_importacao_id);
CREATE INDEX IF NOT EXISTS idx_alertas_tipo_nivel
  ON profor_2022_rateio_import_alertas(tipo, nivel);

-- Índices de profor_2022_revisao_divergencias
CREATE INDEX IF NOT EXISTS idx_revisao_divergencias_status
  ON profor_2022_revisao_divergencias(status);
CREATE INDEX IF NOT EXISTS idx_revisao_divergencias_tipo
  ON profor_2022_revisao_divergencias(tipo_alerta);
CREATE INDEX IF NOT EXISTS idx_revisao_divergencias_nivel
  ON profor_2022_revisao_divergencias(nivel);
CREATE INDEX IF NOT EXISTS idx_revisao_divergencias_convenio
  ON profor_2022_revisao_divergencias(numero_convenio);
CREATE INDEX IF NOT EXISTS idx_revisao_divergencias_chave_item
  ON profor_2022_revisao_divergencias(chave_item);

-- Índices de profor_2022_revisao_decisoes
CREATE INDEX IF NOT EXISTS idx_revisao_decisoes_divergencia
  ON profor_2022_revisao_decisoes(divergencia_id);

-- Índices de profor_2022_revisao_logs
CREATE INDEX IF NOT EXISTS idx_revisao_logs_entidade
  ON profor_2022_revisao_logs(entidade_tipo, entidade_id);

-- ---------------------------------------------------------------------------
-- 20. faf_2021_itens
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS faf_2021_itens (
  item_id text PRIMARY KEY,
  indice_dados_base integer,
  uf text NOT NULL,
  objeto text NOT NULL,
  quantidade numeric(14,2) NOT NULL DEFAULT 0,
  valor_unitario numeric(15,2) NOT NULL DEFAULT 0,
  valor_total numeric(15,2) NOT NULL DEFAULT 0,
  valor_executado numeric(15,2) NOT NULL DEFAULT 0,
  observacao_execucao text,
  atualizado_em timestamptz,
  instrumento text NOT NULL DEFAULT 'FAF 2021',
  payload_original_json jsonb,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT faf_2021_itens_valor_total_nao_negativo CHECK (valor_total >= 0),
  CONSTRAINT faf_2021_itens_valor_executado_nao_negativo CHECK (valor_executado >= 0)
);

CREATE INDEX IF NOT EXISTS idx_faf_2021_itens_uf
  ON faf_2021_itens (uf);

CREATE INDEX IF NOT EXISTS idx_faf_2021_itens_instrumento
  ON faf_2021_itens (instrumento);
