-- Historico operacional do PAD do PROFOR 2022. Acesso exclusivo pelo backend.

CREATE TABLE IF NOT EXISTS public.profor_2022_pad_atualizacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  job_id text,
  origem text NOT NULL DEFAULT 'TRANSFEREGOV',

  status text NOT NULL,
  resultado text,

  iniciado_em timestamptz NOT NULL DEFAULT now(),
  concluido_em timestamptz,

  total_itens_antes integer,
  total_itens_depois integer,

  total_novos integer NOT NULL DEFAULT 0,
  total_removidos integer NOT NULL DEFAULT 0,
  total_alterados integer NOT NULL DEFAULT 0,

  total_valor_previsto_antes numeric(18,2),
  total_valor_previsto_depois numeric(18,2),
  delta_valor_previsto numeric(18,2),

  total_valor_executado_antes numeric(18,2),
  total_valor_executado_depois numeric(18,2),
  delta_valor_executado numeric(18,2),

  total_saldo_antes numeric(18,2),
  total_saldo_depois numeric(18,2),
  delta_saldo numeric(18,2),

  tem_pendencias_revisao boolean NOT NULL DEFAULT false,
  total_pendencias_revisao integer NOT NULL DEFAULT 0,

  versao_snapshot text,
  versao_comparador text,

  mensagem_erro text,
  metadados_json jsonb NOT NULL DEFAULT '{}'::jsonb,

  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT ck_profor_2022_pad_atualizacoes_status
    CHECK (status IN ('EM_EXECUCAO', 'CONCLUIDA', 'FALHOU')),

  CONSTRAINT ck_profor_2022_pad_atualizacoes_resultado
    CHECK (
      resultado IS NULL
      OR resultado IN ('SEM_ALTERACOES', 'COM_ALTERACOES')
    )
);

CREATE INDEX IF NOT EXISTS idx_profor_2022_pad_atualizacoes_iniciado
  ON public.profor_2022_pad_atualizacoes (iniciado_em DESC);

CREATE INDEX IF NOT EXISTS idx_profor_2022_pad_atualizacoes_job
  ON public.profor_2022_pad_atualizacoes (job_id);

CREATE INDEX IF NOT EXISTS idx_profor_2022_pad_atualizacoes_resultado
  ON public.profor_2022_pad_atualizacoes (resultado);

CREATE TABLE IF NOT EXISTS public.profor_2022_pad_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  atualizacao_id bigint NOT NULL,
  momento text NOT NULL,

  checksum text NOT NULL,
  versao_snapshot text,
  parser_versao text,
  origem text,

  gerado_em timestamptz NOT NULL,
  snapshot_json jsonb NOT NULL,
  resumo_json jsonb NOT NULL DEFAULT '{}'::jsonb,

  criado_em timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_profor_2022_pad_snapshot_atualizacao
    FOREIGN KEY (atualizacao_id)
    REFERENCES public.profor_2022_pad_atualizacoes(id)
    ON DELETE RESTRICT,

  CONSTRAINT ck_profor_2022_pad_snapshot_momento
    CHECK (momento IN ('ANTES', 'DEPOIS')),

  CONSTRAINT uq_profor_2022_pad_snapshot_momento
    UNIQUE (atualizacao_id, momento)
);

CREATE INDEX IF NOT EXISTS idx_profor_2022_pad_snapshots_atualizacao
  ON public.profor_2022_pad_snapshots (atualizacao_id);

CREATE INDEX IF NOT EXISTS idx_profor_2022_pad_snapshots_checksum
  ON public.profor_2022_pad_snapshots (checksum);

CREATE TABLE IF NOT EXISTS public.profor_2022_pad_alteracoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  atualizacao_id bigint NOT NULL,
  chave_alteracao text NOT NULL,

  tipo text NOT NULL,

  numero_convenio text,
  uf text,

  chave_item_anterior text,
  chave_item_nova text,

  origem_pareamento text,

  descricao_anterior text,
  descricao_nova text,

  area_anterior text,
  area_nova text,

  natureza_anterior text,
  natureza_nova text,

  classificacao_estado text NOT NULL DEFAULT 'NAO_APLICAVEL',

  revisao_divergencia_id bigint,
  decisao_substituto_id bigint,

  campos_alterados_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  item_anterior_json jsonb,
  item_novo_json jsonb,

  criado_em timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT fk_profor_2022_pad_alteracao_atualizacao
    FOREIGN KEY (atualizacao_id)
    REFERENCES public.profor_2022_pad_atualizacoes(id)
    ON DELETE RESTRICT,

  CONSTRAINT fk_profor_2022_pad_alteracao_revisao
    FOREIGN KEY (revisao_divergencia_id)
    REFERENCES public.profor_2022_revisao_divergencias(id)
    ON DELETE SET NULL,

  CONSTRAINT fk_profor_2022_pad_alteracao_decisao
    FOREIGN KEY (decisao_substituto_id)
    REFERENCES public.profor_2022_revisao_decisoes(id)
    ON DELETE SET NULL,

  CONSTRAINT ck_profor_2022_pad_alteracao_tipo
    CHECK (tipo IN ('NOVO', 'REMOVIDO', 'ALTERADO')),

  CONSTRAINT ck_profor_2022_pad_classificacao_estado
    CHECK (
      classificacao_estado IN (
        'NAO_APLICAVEL',
        'PRESERVADA',
        'HERDADA_SUBSTITUTO',
        'PENDENTE_REVISAO'
      )
    ),

  CONSTRAINT uq_profor_2022_pad_alteracao_chave
    UNIQUE (atualizacao_id, chave_alteracao)
);

CREATE INDEX IF NOT EXISTS idx_profor_2022_pad_alteracoes_atualizacao
  ON public.profor_2022_pad_alteracoes (atualizacao_id);

CREATE INDEX IF NOT EXISTS idx_profor_2022_pad_alteracoes_tipo
  ON public.profor_2022_pad_alteracoes (tipo);

CREATE INDEX IF NOT EXISTS idx_profor_2022_pad_alteracoes_convenio_uf
  ON public.profor_2022_pad_alteracoes (numero_convenio, uf);

CREATE INDEX IF NOT EXISTS idx_profor_2022_pad_alteracoes_revisao
  ON public.profor_2022_pad_alteracoes (revisao_divergencia_id);

CREATE INDEX IF NOT EXISTS idx_profor_2022_pad_alteracoes_decisao
  ON public.profor_2022_pad_alteracoes (decisao_substituto_id);

ALTER TABLE public.profor_2022_pad_atualizacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profor_2022_pad_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profor_2022_pad_alteracoes ENABLE ROW LEVEL SECURITY;

-- As tabelas nao se destinam ao Data API. Mantem o acesso pela conexao do backend.
REVOKE ALL PRIVILEGES ON TABLE public.profor_2022_pad_atualizacoes FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.profor_2022_pad_snapshots FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.profor_2022_pad_alteracoes FROM anon, authenticated;
